language: python
python:
- 3.5
services:
- postgresql
install: pip install -r requirements.txt
before_script:
- psql -c 'CREATE DATABASE foodship;' -U postgres
- psql -c 'CREATE EXTENSION postgis;' -U postgres -d foodship
after_success:
- git checkout -b deploy
- git add .
- git -c user.name='travis' -c user.email='travis' commit -m "Deploy"
- git pull
- git push https://$GITHUB_TOKEN@github.com/foodshipper/server-application.git
script: python -m unittest discover -s . -p '*_test.py'
env:
  matrix:
  - DB_USER=postgres DB_PASS= DB_HOST=localhost DB_NAME=foodship FIREBASE_KEY=no_key
    PRODUCTIVE=0
  global:
  - secure: HliHHFCLkg39AcJjIRjzMIxgNjTyXM+BGMQN5GK+ZmN+5tVQGvIsS3HM7QmEEbWpvmQ+3m4gyZlx4ht+ae8uIER5OS7EJwg8Tiqo3g/vi63fgc2bDgiUkm5Mh5UJmWzHHi1YGMTJpimmrW/Xx6jeBUmQ6P/T7tEgSdHoBmh3RxQlJEm934TRUWgsbuwbxV4Icpf5pd2+57jglsliOr+PlL9VRkjU2LwPLC/FXWIsro3WcZfEbv8Tga3icnC6KKLpbQPtT82+mT48JOdCstBv9UNjzWGQqD+lVddM+/8AsTWS0YEjUMeAPNf82XSP6Xn0HuFi0m70FNT6P/z9k+vRMHwqjq/AyfHDHlH0cTfXVCg71cVL9/5i2owrVmKZnCVXZpbKz1Im7ahsAz7YKO4kp+PEeqgBMiprmk0T/6B0zMWrHwmKrS/ANNw2BB7yUYnFjiVD4FyzNG81WLZhzZVuuHg+Y+4HAiGm7t51aZvI4SEBzpmvwmYQkRJ75m06aVCKohwRtmTi2anDjHoSJF47RkWrO+rs1OAsU/t+fTVSQGZWmN9SsgvpQhudF2tBnw8sZORvAn2XHUoai6+0R1eqNuWS0qgGW1miv4XtspaiihXJLfKl7q0/l4aN65LWbaIaIB0yEAc1Tn+PaQBQ0JWhEPECmvpuulu3kwscjr/DufM=
  - secure: Vxic8bRNbGMaJpNYubw3d2KiTdEksdYPoRUYjVxUl0pRwHoezhTvz4tj6Zg783MeqNt7L1Xbt2C83N8TWcS08Qz+MqdiwXMjOmnFpeqKDFMNz6G8JyYD2ueG9EqkXgRzJTrHODiITl9LFGqrNhc645lAyMkcp6dmfOcQ6EndyNVTS6OZoegnPec67cu2FA28xu9GPFG9B4qeimR6PCeamk7WvKz5a3AwxtOqxgLIJlZHQatWeNruDMgKk4iU/QbU8I8ChaOnwziinSkJs2+zzXvbvE1k9xaSY2Ks50i1UqRaXghFZBpk+3LfzY4d16K0ugHGFOQAuBDTj22YsJGn9RXc19+uj0mig8EWFedrG3k/mRLI13hLsgljtRJDruUDtbeLYalcg0rWHvBbQw4TfU4x81C7Ls+H+YgcohCu/6gc8qcZLUacFWVMa/j6xIt+9dXb0+EGuUaMFqTyYmagoZSkbZ9q0kn3KGLIKWmhWSYwqJ68jy3Sv+EY/AWsAV6Gi4isbk1+V04LExOHQcShPasHmYnZs0hYmKt9iXVwEggy4FZxpvgw2iZtgrj5SbB0/aO/Kc+leev0v1DZGdvxdWO27Hm5dCPMIa6T4RdGZ1/2LZIZrOLpArwQngznoIm/YQkPro5eV87DS6Qr6asYYVQDXQvwyryhhs3L7nqn1u8=
  - secure: U4ZTQ3oHXfg1YPvB/PWc7VpJEXYhX1U2nI4ITriGOkz9byku1M/F9AgRLvysMXWV6RnHtLLL26w+ugpxqQQB/pDHWOP4B6j5EdLECkRwQVyBiPCpyvjS7z3BuCXSDYQNcQstodNc7u5WfYUs8xwoUM9Q2UrNpBheDBnBwgOe0Ndy/0+u4EKF4lEK7ebB9ySW5kxhii0iJxBcZtHpK3+b+yPKm5jcLxITRFUjxzy4CaqyJO1jsarBLugT68GYkkxCnzVnfsgO2c+7TSexa+MloG7l8SJ8SUzffv+YESexHhtTLJfjCX+//pdjCxWJgXOEO6AeLlWQ0DfL0e3TSlSuZjINvld64fzL9ml5hsmaWQ6iyAm9Y8dk+HYzZt0BADwf8x5WvP5Dr9LnpZfkLx04PkIJA6KEvGZkNrg5S95RWaQA4W5GEWD/nek/hzhB8Ox82a37eyhYoPuVlJ4VSRZjKKDgR8PM2OCgZeCNI8sWi94Q1AAjb0gSA2Rq2mKnXrZHk6HuxzUG4xXYsB7hxU4+QujVK2yVxpXa3Fe6UbjPlCPb+a2SBV5d2r9dihp1cvXgxfW0+pxyzfE/hAgbXQF7oEf4H0VJM877npuzEI5ZGvNayvtXv/McHebXUmq52zAT7slFKA3fn2joYkRpE/z0+v9YjVE8c0S4eGFqj+eA0pg=
branches:
  except:
  - deploy
