language: python
python:
    - 3.5
services:
  - postgresql
before_script:
  - psql -c 'create database foodship;' -U foodship
env:
  - DB_USER=foodship
  - DB_PASS=
  - DB_HOST=localhost
  - DB_NAME=foodship