language: python
python:
- 3.5
services:
- postgresql
install: pip install -r requirements.txt
before_script:
  - psql -c 'CREATE DATABASE foodship;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d foodship
after_success:
  - git checkout -b deploy
  - git add .
  - git -c user.name='travis' -c user.email='travis' commit -m "Deploy"
  - git push -f -q &2>/dev/null
script: python -m unittest discover -s . -p '*_test.py'
env:
- DB_USER=postgres DB_PASS= DB_HOST=localhost DB_NAME=foodship