language: python
python:
- 3.5
services:
- postgresql
install: pip install -r requirements.txt
before_script:
- psql -c 'CREATE DATABASE foodship;' -U postgres
- psql -c 'CREATE EXTENSION postgis;' -U postgres -d foodship
after_success:
- git checkout -b deploy
- git add .
- git -c user.name='travis' -c user.email='travis' commit -m "Deploy"
- git pull
- git push https://$GITHUB_TOKEN@github.com/foodshipper/server-application.git
script: python -m unittest discover -s . -p '*_test.py'
env:
  matrix:
  - DB_USER=postgres DB_PASS= DB_HOST=localhost DB_NAME=foodship FIREBASE_KEY=no_key
  global:
    secure: HliHHFCLkg39AcJjIRjzMIxgNjTyXM+BGMQN5GK+ZmN+5tVQGvIsS3HM7QmEEbWpvmQ+3m4gyZlx4ht+ae8uIER5OS7EJwg8Tiqo3g/vi63fgc2bDgiUkm5Mh5UJmWzHHi1YGMTJpimmrW/Xx6jeBUmQ6P/T7tEgSdHoBmh3RxQlJEm934TRUWgsbuwbxV4Icpf5pd2+57jglsliOr+PlL9VRkjU2LwPLC/FXWIsro3WcZfEbv8Tga3icnC6KKLpbQPtT82+mT48JOdCstBv9UNjzWGQqD+lVddM+/8AsTWS0YEjUMeAPNf82XSP6Xn0HuFi0m70FNT6P/z9k+vRMHwqjq/AyfHDHlH0cTfXVCg71cVL9/5i2owrVmKZnCVXZpbKz1Im7ahsAz7YKO4kp+PEeqgBMiprmk0T/6B0zMWrHwmKrS/ANNw2BB7yUYnFjiVD4FyzNG81WLZhzZVuuHg+Y+4HAiGm7t51aZvI4SEBzpmvwmYQkRJ75m06aVCKohwRtmTi2anDjHoSJF47RkWrO+rs1OAsU/t+fTVSQGZWmN9SsgvpQhudF2tBnw8sZORvAn2XHUoai6+0R1eqNuWS0qgGW1miv4XtspaiihXJLfKl7q0/l4aN65LWbaIaIB0yEAc1Tn+PaQBQ0JWhEPECmvpuulu3kwscjr/DufM=
branches:
  except:
    - deploy